@startuml

participant evproposer
collections evacceptor

evacceptor -> evacceptor++: **send_acceptor_state ()** \nacceptor_set_current_state ()
evacceptor -> evproposer++: peer_send_paxos_message ()
deactivate evacceptor

evproposer -> evproposer++: **evproposer_handle_acceptor_state ()** \nproposer_receive_acceptor_state ()

rnote over evproposer
    //proposer_receive_acceptor_state//
    ---
    1. Compare //"p->max_trim_iid < state->trim_iid)"//
    2. Remove instances older than given //iid// for,
        - //prepare_instances//
        - //accept_instances//
end note

deactivate evproposer
deactivate evproposer


evacceptor -> evacceptor++: **send_acceptor_state ()** \nacceptor_set_current_state ()
evacceptor -> evproposer++: peer_send_paxos_message ()

====

@enduml