@startuml paxos_types

' online plantuml server : https://www.plantuml.com/plantuml/uml/

' paxos_value
struct paxos_value {
    {field} paxos_value_len : int
    {field} paxos_value_val : char*
}

' paxos_prepare
struct paxos_prepare
{
    {field} iid : uint32_t
    {field} ballot : uint32_t
}

' paxos_promise
struct paxos_promise
{
    {field} aid : uint32_t
    {field} iid : uint32_t
    {field} ballot : uint32_t
    {field} value_ballot : uint32_t
    {field} value : paxos_value
}

paxos_promise *-- "value" paxos_value

' paxos_accept
struct paxos_accept
{
    {field} iid : uint32_t
    {field} ballot : uint32_t
    {field} value : paxos_value
}

paxos_accept *-- "value" paxos_value

' paxos_accepted
struct paxos_accepted
{
    {field} aid : uint32_t
    {field} iid : uint32_t
    {field} ballot : uint32_t
    {field} value_ballot : uint32_t
    {field} value : paxos_value
}

paxos_accepted *-- "value" paxos_value

' paxos_preempted
struct paxos_preempted {
    {field} aid : uint32_t
    {field} iid : uint32_t
    {field} ballot : uint32_t
}

struct paxos_repeat {
    {field} from : uint32_t
    {field} to : uint32_t
}

struct paxos_trim {
    {field} iid : uint32_t
}

struct paxos_acceptor_state {
    {field} aid : uint32_t
    {field} trim_iid : uint32_t
}

struct paxos_client_value {
    {field} value : paxos_value
}

paxos_client_value *-- "value" paxos_value

' paxos_message_type
enum paxos_message_type
{
    PAXOS_PREPARE    
    PAXOS_PROMISE    
    PAXOS_ACCEPT    
    PAXOS_ACCEPTED    
    PAXOS_PREEMPTED    
    PAXOS_REPEAT    
    PAXOS_TRIM    
    PAXOS_ACCEPTOR_STATE    
    PAXOS_CLIENT_VALUE
}    

struct paxos_message {
    {field} type : paxos_message_type
    {field} u : //Anonymous UNION//
}

entity "Anonymous UNION" {
    prepare : paxos_prepare
    promise : paxos_promise
    accept : paxos_accept
    accepted : paxos_accepted 
    preempted : paxos_preempted 
    repeat : paxos_repeat 
    trim : paxos_trim 
    state : paxos_acceptor_state 
    client_value : paxos_client_value 
}

paxos_message *-- "u" "Anonymous UNION"

"Anonymous UNION" *-- "prepare" paxos_prepare
"Anonymous UNION" *-- "promise" paxos_promise
"Anonymous UNION" *-- "accept" paxos_accept
"Anonymous UNION" *-- "accepted" paxos_accepted
"Anonymous UNION" *-- "preempted" paxos_preempted
"Anonymous UNION" *-- "repeat" paxos_repeat 
"Anonymous UNION" *-- "trim" paxos_trim 
"Anonymous UNION" *-- "state" paxos_acceptor_state 
"Anonymous UNION" *-- "client_value" paxos_client_value 


@enduml

